name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: ['pca10056']
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true      
        
    - name: Install Toolchains
      run: |
        pip3 install adafruit-nrfutil
        wget https://www.nordicsemi.com/api/sitecore/Products/DownloadPlatform --post-data=fileid=8F19D314130548209E75EFFADD9348DB -O cli-tools.tar
        tar -xv -f cli-tools.tar
        echo "::add-path::$GITHUB_WORKSPACE/mergehex"
        npm install --global xpm
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest
        echo "::add-path::`echo $HOME/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin`"
    
    - name: Build
      run: |
        echo $PATH
        python3 tools/build_all.py
        #run: python3 tools/build_all.py ${{ matrix.example }}
